name: static-clang-tools-binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4\

      - name: Set up C++ compiler on Windows
        if: runner.os == 'Windows'
        uses: actions/setup-msbuild@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: make run
